project:
  type: book
  output-dir: docs

book:
  title: "R for Data Science (2e) - Solutions to Exercises"
  reader-mode: true

  page-footer:
    left: |
      The Solutions to Exercises for R for Data Science (2e) was written by
      Jabir Ghaffar, Davon Person, and Mine Çetinkaya-Rundel.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  site-url: https://r4ds.hadley.nz/
  repo-url: https://github.com/mine-cetinkaya-rundel/r4ds-solutions/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd

    - part: "Whole game"
      chapters:
        - data-visualize.qmd
        - workflow-basics.qmd
        - data-transform.qmd
        - workflow-style.qmd
        - data-tidy.qmd
        - workflow-scripts.qmd
        - data-import.qmd
        - workflow-help.qmd

    - part: "Visualize"
      chapters:
        - layers.qmd
        - EDA.qmd
        - communication.qmd

    - part: "Transform"
      chapters:
        - logicals.qmd
        - numbers.qmd
        - strings.qmd
        - regexps.qmd
        - factors.qmd
        - datetimes.qmd
        - missing-values.qmd
        - joins.qmd

    - part: "Import"
      chapters:
        - spreadsheets.qmd
        - databases.qmd
        - arrow.qmd
        - rectangling.qmd
        - webscraping.qmd

    - part: "Program"
      chapters:
        - functions.qmd
        - iteration.qmd
        - base-R.qmd

    - part: "Communicate"
      chapters:
        - quarto.qmd
        - quarto-formats.qmd

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "Jabir Ghaffar, Davon Person, and Mine Çetinkaya-Rundel"
    callout-appearance: simple

editor: visual

execute:
  freeze: auto
